### ISSUE TITLE
415 while using contentType 'multipart/form-data' 

### ISSUE THREAD

**Issue by Cajuteq** [blomqma/next-rest-framework#16]
Hi, I'm using this lib to create a swagger doc,
I'm using File Uploads, and I am using a openApiSpec to create the field in the swagger like this
``` 
        openApiSpec: {
			requestBody: {
				content: {
					'multipart/form-data': {
						schema: {
							required: ['files'],
							type: 'object',
							properties: {
								files: {
									title: 'Files',
									type: 'array',
									items: {
										type: 'string',
										format: 'binary',
									},
								},
							},
						},
					},
				},
			},
		},
```

This works in creating files array in Swagger UI where I can upload one or several Files but 
when I try to check on the input using
```
        input: {
			contentType: 'multipart/form-data',
                        body: z.any(),
	},
```
I recieve a 415 Invalid media type, 

I tryed commenting the `body: z.any()` but it doesn't change a thing,

I also tryed with `contentType: '*/*',` with no success,

I suspect it is due to the fact that the Content-Type header include the boundary in case of multipart/form-data, like this
```
Content-Type | multipart/form-data; boundary=---------------------------301637601939585445731264645304
```

As we cannot use body checking without contentType, I'm out of idea on how to make this work while keeping the validation with Zod.

I would like to make proper validation like the following :
```
const fileScheme = z
	.any()
	.refine((files) => files?.length === 0, 'File is required.') // if no file files?.length === 0, if file files?.length === 1
	.refine((files) => files?.[0]?.size >= MAX_FILE_SIZE, `Max file size is 5MB.`) // this should be greater than or equals (>=) not less that or equals (<=)
	.refine(
		(files) => ACCEPTED_IMAGE_TYPES.includes(files?.[0]?.type),
		'.jpg, .jpeg, .png and .webp files are accepted.'
	);
```

Any help appreciated

**Comment by blomqma** [comment]
Thanks for the issue @Cajuteq. A bug with the 415 status response has now been addressed in release [v0.3.5](https://github.com/blomqma/next-rest-framework/releases/tag/v0.3.5). The content type header validation should now take the header parameters into account, addressing your issue with the error response so you should still be able to use the framework.

Note that this doesn't solve your other problem where you would like to validate the form data (including files) with a Zod schema. Currently the runtime validation is only limited to request bodies. Since you pointed this problem, I will be next working on adding support for validation of requests containing form and multipart data where the content is not necessarily in the request body. In the mean time, you could handle the validation of the form data directly in your request handler with your own validation. I will keep this issue open until support for validating form data and files is done.

**Comment by Cajuteq** [comment]
Thanks a lot, I confirm that 0.3.5 solves the first part of the problem,

For the second part, I use formidable and I am able to leverage filter() to make the validation, I now have a functional upload with related Swagger and (in-handler) validation;

For the record, I use 
```
input: {
  contentType: 'multipart/form-data',
  body: z.any(),
},
openApiSpec: {
  requestBody: {
    content: {
      'multipart/form-data': {
        schema: {
          required: ['files'],
          type: 'object',
          properties: {
            files: {
              title: 'Files',
              type: 'array',
              items: {
                type: 'string',
                format: 'binary',
              },
            },
          },
        },
      },
    },
  },
},
```

**Comment by blomqma** [comment]
Posting an update on this after some further consideration: With the content-type header validation fixed, custom validation logic that you pointed should be now possible using custom validation logic.  Adding built-in support for validation for data that is encoded into the headers would require new dependencies and is not trivial to solve for varying use cases. Therefore I personally don't consider this having a high priority at the moment but I am willing to change my mind and come back to this later if there will be a wider community need for it. While I will personally not look further into this for now, all contributions are welcome but I'm closing this issue as solved for now.
