### ISSUE TITLE
Does this work in production (vercel)?

### ISSUE THREAD

**Issue by bramses** [blomqma/next-rest-framework#25]
Hi, firstly, thanks for this framework! It's great!

One question: when I visit `/api` in localhost the API spec shows up just fine, but when I deploy to Vercel I get the error

```
{"message":"An unknown error occurred, trying again might help."}

// and in vercel logs...

Next REST Framework initialized! 🚀
Swagger UI: https://next-chatgpt-plugins-api-starter-fu18i78nv-bramses-vercel.vercel.app/api
OpenAPI JSON: https://next-chatgpt-plugins-api-starter-fu18i78nv-bramses-vercel.vercel.app/api/openapi.json
OpenAPI YAML: https://next-chatgpt-plugins-api-starter-fu18i78nv-bramses-vercel.vercel.app/api/openapi.yaml
Next REST Framework encountered an error - suppressed in production mode.
```

Is this intended? I'm under the assumption that it is due to `fs` being required, or the `next-rest-framework/client.ts
` not propagating but I'm not 100% sure.

Thanks!

EDIT: and if not, is it possible to download the up to date `openapi.json` or `openapi.yaml` spec? I might be able to have that auto trigger on the build process and set it at some static URL

**Comment by blomqma** [comment]
Hello and thanks for opening this issue. I was able to reproduce the issue and have taken several measures to address it in the latest [v0.5.1](https://github.com/blomqma/next-rest-framework/releases/tag/v0.5.1) release. The dynamic file system calls indeed caused the bug when using the framework with a Next.js project in Vercel. Instead of making dynamic file system calls, the generated OpenAPI spec is now cached as a JSON file in the project.

So in the future, whenever developing your application locally with Next REST Framework, you will see a file called `openapi.json` generated at the root of your project. During local development, this file is dynamically regenerated whenever your make changes to your API routes and call any of the reserved OpenAPI endpoints of the framework:
- `/api`
- `/api/openapi.json`
- `/api/openapi.yaml`

The generated `openapi.json` file should remain under version control and is never mutated in production by the framework but instead it will be the single source of truth for the OpenAPI specification in production.

To make the framework more robust and production ready, I have also added automation to deploy a live demo application from the `apps/example` to test all future changes in production: https://next-rest-framework-demo.vercel.app/api

So to answer your question: All releases of the framework so far have been marked as pre-releases i.e. not ready for production but with these changes live I can see the maturity of the framework evolving closer to something that could be used in production.

I would also value your feedback on these changes as you had these specific issue and I believe they both have now been solved.

**Comment by bramses** [comment]
Thank you for the detailed response! I like the idea of `openapi.json` being at the root, even in prod. Since submitting this issue, I've switched to using [next-swagger-doc](https://www.npmjs.com/package/next-swagger-doc) for the current ChatGPT Plugin I'm working on (I'm in the alpha) but will try your updates on my next plugin :).

*P.S. you may want to get this production ready, since [you'll likely be receiving a lot of attention](https://platform.openai.com/docs/plugins/getting-started/openapi-definition) as more developers are onboarded to plugins!*
